server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: management
    version: 0.0.1
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid, profile
            authorization-grant-type: authorization_code
            client-id: backend
            client-secret: hD8dQ8n0nQzzpAUbN8RNhyQQGKqqKKVj
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8282/realms/management
            jwk-set-uri: http://localhost:8282/realms/management/protocol/openid-connect/certs
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/management

  datasource:
    url: jdbc:postgresql://localhost:5432/management-db
    username: admin
    password: admin
    hikari:
      schema: management
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: public
    default-schema: public
    locations: classpath:db/migration

oAuth_security_schema: my_oAuth_security_schema
keycloak-auth-redirect: http://localhost:8282/realms/management/protocol/openid-connect/auth